DROP DATABASE IF EXISTS blog_db;
CREATE DATABASE blog_db;

USE blog_db;

CREATE TABLE blog
(
id INT NOT NULL AUTO_INCREMENT,
user_name VARCHAR(255) NOT NULL,
brewery VARCHAR(255),
main_text_field VARCHAR(1000) NOT NULL,
comments VARCHAR(1000),
PRIMARY KEY(id)
); 